// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEKl-4Sz93CXj4Cal95d4Uc56UmRPIOuI',
    appId: '1:1038489830914:web:445bfd00c78e21fb99091b',
    messagingSenderId: '1038489830914',
    projectId: 'qotton-b5ad3',
    authDomain: 'qotton-b5ad3.firebaseapp.com',
    storageBucket: 'qotton-b5ad3.firebasestorage.app',
    measurementId: 'G-BVJM1KP7Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfoAHUOA5_ok4kF68BrZLMII1JnckGVEw',
    appId: '1:1038489830914:android:637e472a1116533399091b',
    messagingSenderId: '1038489830914',
    projectId: 'qotton-b5ad3',
    storageBucket: 'qotton-b5ad3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgtuGrIZK1CTGNHScNXnKvRJEKi6-UFdA',
    appId: '1:1038489830914:ios:6028318eaf4a729599091b',
    messagingSenderId: '1038489830914',
    projectId: 'qotton-b5ad3',
    storageBucket: 'qotton-b5ad3.firebasestorage.app',
    iosBundleId: 'com.example.qottonShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgtuGrIZK1CTGNHScNXnKvRJEKi6-UFdA',
    appId: '1:1038489830914:ios:6028318eaf4a729599091b',
    messagingSenderId: '1038489830914',
    projectId: 'qotton-b5ad3',
    storageBucket: 'qotton-b5ad3.firebasestorage.app',
    iosBundleId: 'com.example.qottonShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEKl-4Sz93CXj4Cal95d4Uc56UmRPIOuI',
    appId: '1:1038489830914:web:85e5c484a287ce6599091b',
    messagingSenderId: '1038489830914',
    projectId: 'qotton-b5ad3',
    authDomain: 'qotton-b5ad3.firebaseapp.com',
    storageBucket: 'qotton-b5ad3.firebasestorage.app',
    measurementId: 'G-FKRM8KMV8L',
  );
}
